### ISSUE TITLE
Maybe remove the requirement for the sets training and test domains to be disjoint

### ISSUE THREAD

**Issue by agisga** [smilesun/DomainLab#9]
Maybe remove the requirement for the sets training and test domains to be disjoint.
Potentially, we could replace it with a warning.

https://github.com/smilesun/libDG/blob/e8227b7c42db7388cff482802cdfaf6191050ef8/libdg/tasks/a_task.py#L148

**Comment by smilesun** [comment]
Fixed in the pull request
